import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import type { Metadata } from "next";
import { extractRouterConfig } from "uploadthing/server";
import Header from "@/components/header"; // Adjust path if needed
import { ourFileRouter } from "@/lib/uploadthing";
import "./globals.css";
// import { auth } from "@/auth";
// import SessionProvider from "@/providers/session-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-900 text-gray-100">
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
