import Header from "@/components/header"; // Adjust path if needed
import { ourFileRouter } from "@/lib/uploadthing";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import { extractRouterConfig } from "uploadthing/server";
import "./globals.css";
import ToastContainerIcon from "@/components/toast-container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-900 text-gray-100">
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <Header />
        <main>{children}</main>
        <div id="menu-root" />
        <ToastContainer
          toastClassName="bg-bg-secondary rounded-lg border border-border-primary text-text-primary"
          autoClose={3000}
          hideProgressBar
          theme="dark"
          icon={ToastContainerIcon}
        />
      </body>
    </html>
  );
}
